INSERT INTO ESTUDANTE VALUES (15, 1, 1, 1, 7, 8, 9, 1l, 'PRIMERO_ANO_ENSINO_MEDIO', 'Joao', 'da Silva');
INSERT INTO ESTUDANTE VALUES (15, 1, 1, 1, 8, 7, 4, 2l, 'PRIMERO_ANO_ENSINO_MEDIO', 'Gabriel', 'Angelo');
INSERT INTO ESTUDANTE VALUES (15, 1, 1, 1, 8, 4, 10, 3l, 'PRIMERO_ANO_ENSINO_MEDIO', 'Bruno', 'Ribeiro');